INSERT INTO countries ( country_name, country_code ) VALUES
( 'Cameroon', 'CMR' ), 
( 'Angola', 'AGO' ), 
( 'Bahamas', 'BS' ), 
( 'France', 'FRA' ), 
( 'Germany', 'DEU' ), 
( 'Ivory Coast', 'CIV' ), 
( 'Nigeria', 'NGA' ), 
( 'North Korea', 'PRK' ), 
( 'Russia', 'RUS' ),
( 'South Africa', 'ZAF' ),
( 'United States of America', 'USA' );

INSERT INTO towns ( town_name, country_code ) VALUES 
( 'Yaounde', 'CMR' ),
( 'Douala', 'CMR' ),
( 'Luanda', 'AGO' ),
( 'Lubango', 'AGO' ),
( 'Nassau', 'BS' ),
( 'Paris', 'FRA' ),
( 'Nice', 'FRA' ),
( 'Berlin', 'DEU' ),
( 'Munich', 'DEU' ),
( 'Abidjan', 'CIV' ),
( 'Yamoussoukro', 'CIV' ),
( 'Lagos', 'NGA' ),
( 'Abuja', 'NGA' ),
( 'Pyongyang', 'PRK' ),
( 'Moscou', 'RUS' ),
( 'Belgorod', 'RUS' ),
( 'Washington', 'USA' ),
( 'Johannesburg', 'ZAF' ),
( 'Pretoria', 'ZAF' ),
( 'New-York', 'USA' );